### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by emzero** [microsoftgraph/nodejs-connect-rest-sample#68]
Cloned the repo, created the app, configured the client id and secret. 
The app runs at localhost:3000, authorization recognizes my app and when I allow it, the app goes back to localhost:3000 but throws the following error:

```
TypeError: Cannot read property '0' of undefined
    at renderSendMail (D:\Desktop\react\nodejs-connect-rest-sample\routes\index.js:60:43)
    at router.get (D:\Desktop\react\nodejs-connect-rest-sample\routes\index.js:29:5)
    at Layer.handle [as handle_request] (D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\layer.js:95:5)
    at D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Desktop\react\nodejs-connect-rest-sample\node_modules\express\lib\router\index.js:174:3)
```

**Comment by emzero** [comment]
Nevermind. It works now. Don't know what happened before though.

**Comment by sonalchhoda** [comment]
I am getting the same issue ...please let me know the resolution
